// All 12 legal page contents. Designed to be editorial, not boring.
export const LEGAL = {
  terms: {
    title: "Terms of Service",
    eyebrow: "The agreement",
    pull: "By using Sparkd you accept these terms. They protect you, us, and the community.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "1. Acceptance", p: "These Terms govern your access to and use of Sparkd. By creating an account or using the service, you agree to be legally bound. If you do not agree, do not use Sparkd." },
      { h: "2. Eligibility", p: "You must be at least 18 years old. You agree to provide accurate registration data, keep credentials secure, and notify us of unauthorized use. Underage accounts are immediately removed." },
      { h: "3. License & Conduct", p: "We grant you a limited, non-exclusive, non-transferable license to use Sparkd for personal, non-commercial purposes. You will not harass other users, post unlawful content, scrape, reverse engineer, or abuse the platform." },
      { h: "4. Content Ownership", p: "You retain ownership of content you post. You grant Sparkd a worldwide, royalty-free license to host, display, and process it solely to operate the service, including for AI-assisted moderation." },
      { h: "5. Subscriptions & Billing", p: "Paid plans auto-renew monthly until canceled. You can cancel at any time from Billing. Refunds are governed by our Refund & Cancellation Policy." },
      { h: "6. Termination", p: "We may suspend or terminate your account for breaches of these Terms, Community Guidelines, or applicable law. You may delete your account at any time from Settings." },
      { h: "7. Disclaimers & Liability", p: "Sparkd is provided 'as is' without warranties. To the maximum extent permitted by law, our aggregate liability is limited to the greater of (a) the amount you paid us in the prior 12 months, or (b) USD 100." },
      { h: "8. Dispute Resolution", p: "Disputes are resolved by binding arbitration where permitted, on an individual basis. Where mandatory consumer protections apply, this clause is read down to the minimum necessary." },
      { h: "9. Changes", p: "We may update these Terms. Material changes will be notified in-app at least 30 days in advance." },
      { h: "10. Contact", p: "Questions? legal@sparkd.app" },
    ],
  },
  privacy: {
    title: "Privacy Policy",
    eyebrow: "How we handle your data",
    pull: "Privacy isn't a tagline. It's a design constraint we build around every day.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "What we collect", p: "Account info (email, name, DOB), profile content (photos, bio, prompts, interests), usage events, device data, and payment metadata. We do not store full card numbers — Stripe does, under PCI-DSS." },
      { h: "Why we use it", p: "To operate the service, match profiles, prevent fraud, moderate content (with AI assistance), comply with law, and improve product quality." },
      { h: "Legal bases (GDPR)", p: "Contract performance, legitimate interests (safety, security, fraud prevention), consent (marketing, analytics), and legal obligations." },
      { h: "CCPA & DPDP (India)", p: "California and Indian users have rights to access, correct, delete, and object to processing. Sparkd does not sell personal information." },
      { h: "Retention", p: "We keep account data while your account is active and for up to 30 days after deletion, except where retention is required by law (e.g., financial records: 7 years)." },
      { h: "Your rights", p: "Access, rectification, deletion, portability, restriction, and objection. Use the Settings page to download or delete your data instantly." },
      { h: "Children", p: "Sparkd is strictly 18+. We do not knowingly process data from minors. Reported underage accounts are immediately removed." },
      { h: "International transfers", p: "Data may be processed in jurisdictions outside your country, under appropriate safeguards (e.g., Standard Contractual Clauses)." },
      { h: "Contact / DPO", p: "privacy@sparkd.app" },
    ],
  },
  community: {
    title: "Community Guidelines",
    eyebrow: "How we treat each other",
    pull: "Be the version of yourself you'd want to meet.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Be authentic", p: "Use your real name, recent photos, and your own bio. Catfishing is grounds for permanent ban." },
      { h: "Be respectful", p: "No harassment, hate speech, threats, doxxing, or unsolicited explicit content. Period." },
      { h: "Be safe", p: "Do not share personal information of others. Meet in public first. Use the Safety Center tools." },
      { h: "No commercial activity", p: "Sparkd is for dating and connection — not advertising, recruiting, escorting, fundraising, or scams." },
      { h: "No minors", p: "Sparkd is strictly for adults 18+. Any content involving minors is reported to authorities." },
      { h: "Enforcement", p: "Violations may lead to warning, shadow ban, suspension, or permanent removal. AI-assisted moderation reviews reports 24/7; human review escalates serious matters." },
    ],
  },
  cookies: {
    title: "Cookie Policy",
    eyebrow: "What we store on your device",
    pull: "We use cookies sparingly — and you stay in control.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Essential cookies", p: "Required to keep you signed in, route traffic, and prevent abuse. Always on." },
      { h: "Analytics cookies", p: "Help us understand what works. You can disable in the banner or via Settings → Privacy." },
      { h: "Marketing cookies", p: "Used for personalized ads. Opt-out anytime; we will respect your choice on every device." },
      { h: "Third parties", p: "Stripe (payments), Google (auth), and providers required to deliver core functionality may set cookies under their own policies." },
      { h: "Manage", p: "Open the cookie banner from the footer (Cookie Policy → Manage). Your preferences are honored within 24 hours globally." },
    ],
  },
  refund: {
    title: "Refund & Cancellation Policy",
    eyebrow: "Cancel anytime, no hard feelings",
    pull: "Clear, fair, and friction-free — that's a promise.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Cancel anytime", p: "Cancel your subscription in Billing. Access continues until the end of the current billing period." },
      { h: "Auto-renewal disclosure", p: "Subscriptions auto-renew monthly. We email you 24 hours before renewal so there are no surprises." },
      { h: "Refund eligibility", p: "We provide refunds where required by law (e.g., EU 14-day cooling off for digital services not yet used). Outside legal requirements, refunds are evaluated case-by-case for unused premium time." },
      { h: "How to request", p: "Email billing@sparkd.app with your account email and order ID. Most requests are resolved within 5 business days." },
      { h: "Pay-as-you-go", p: "Swipe Packs are non-refundable once any swipe from the pack is used." },
      { h: "Chargebacks", p: "Open a ticket before initiating a chargeback — it's usually faster and friendlier." },
    ],
  },
  safety: {
    title: "Safety Center",
    eyebrow: "Trust, by design",
    pull: "Verified profiles. Blurred photos. AI-assisted moderation. Real humans for review.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Verification", p: "Optional ID verification grants a Trusted badge. Verified-only mode lets you match exclusively with verified users." },
      { h: "Photo blur", p: "Hide your photos until both sides like. Toggle anytime in Safety Center." },
      { h: "Location masking", p: "We never share your exact location — only city-level if you choose to display." },
      { h: "One-tap report & block", p: "Available from any profile or chat. Repeat offenders are shadow banned automatically." },
      { h: "Emergency contact", p: "Save a trusted contact. Trigger a one-tap alert with your last-known city to that contact, no questions asked." },
      { h: "Trans, queer & women safety", p: "Our team prioritizes harassment reports affecting marginalized users. Reports are reviewed by humans within 24 hours." },
    ],
  },
  moderation: {
    title: "Content Moderation Policy",
    eyebrow: "How we keep Sparkd kind",
    pull: "AI flags. Humans decide.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "AI-assisted detection", p: "We use machine learning to detect nudity, hate speech, harassment, scams, spam, and fake accounts. Models are continuously evaluated for fairness." },
      { h: "Human review", p: "Serious cases are escalated to trained reviewers in your region. Decisions can be appealed at appeals@sparkd.app." },
      { h: "Shadow ban", p: "Repeat offenders may be quietly limited (reduced reach) before any account-level action. Transparency reports are published annually." },
      { h: "Transparency", p: "We publish an annual transparency report covering reports, removals, and government data requests." },
    ],
  },
  age: {
    title: "Age Restriction Policy",
    eyebrow: "Strictly 18+",
    pull: "Sparkd is for adults. Always.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Minimum age", p: "You must be 18 or older to register and use Sparkd." },
      { h: "Date-of-birth check", p: "We collect DOB at signup. Inconsistent DOB or selfie-vs-DOB mismatch triggers AI-assisted age estimation review." },
      { h: "Optional ID verification", p: "Premium ID verification grants a badge and unlocks certain trust features." },
      { h: "Reporting underage users", p: "Suspected minors can be reported in-app. We investigate within 24 hours and remove accounts that violate this policy." },
    ],
  },
  "data-deletion": {
    title: "Data Deletion Request",
    eyebrow: "Right to be forgotten",
    pull: "Delete your account and personal data with one button.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Self-service", p: "Settings → Delete account permanently erases profile, photos, swipes, and personal data within 30 days." },
      { h: "What's retained", p: "Anonymized analytics and financial records required by law (typically 7 years)." },
      { h: "Backup propagation", p: "Deletion propagates to backups in the next rotation cycle (≤30 days)." },
      { h: "Contact", p: "privacy@sparkd.app" },
    ],
  },
  consent: {
    title: "User Consent Management",
    eyebrow: "Your choices, on record",
    pull: "Every consent is timestamped, versioned, and revocable.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Signup consent", p: "At signup you accept the Terms, Privacy Policy, and Community Guidelines. The timestamp is recorded." },
      { h: "Cookies", p: "Cookie consent is recorded separately and respected globally for 13 months or until you change it." },
      { h: "Marketing & ads", p: "Personalized advertising requires explicit opt-in (or, where law permits, opt-out)." },
      { h: "Revocation", p: "Withdraw any consent at any time. Withdrawal does not affect prior lawful processing." },
    ],
  },
  dmca: {
    title: "Copyright & DMCA Policy",
    eyebrow: "Intellectual property",
    pull: "We respect creators. Notify us, and we'll act.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Reporting infringement", p: "Send a written notice to dmca@sparkd.app including: identification of the work, the infringing material, your contact info, a good-faith statement, an accuracy statement, and your signature." },
      { h: "Counter-notification", p: "If your content was removed in error, you may submit a counter-notice. We restore access if no court action is filed within 10 business days." },
      { h: "Repeat infringers", p: "We terminate accounts of repeat infringers in appropriate circumstances." },
    ],
  },
  "ai-disclosure": {
    title: "AI Usage Disclosure",
    eyebrow: "Where AI shows up on Sparkd",
    pull: "Transparency about machines, so you can trust the humans.",
    updated: "Last updated: February 2026",
    sections: [
      { h: "Moderation", p: "We use AI to flag harmful text and imagery (nudity, harassment, hate, scams). Flags are reviewed by humans for sensitive cases." },
      { h: "Match recommendations", p: "We use lightweight scoring to surface profiles likely to interest you. You can always reset or browse manually." },
      { h: "Icebreakers", p: "AI can suggest opening messages. They are suggestions, not auto-sent — you review and edit before sending." },
      { h: "Age estimation", p: "AI may estimate age from photos to flag potential underage accounts for human review. We never use estimates for advertising." },
      { h: "Models & vendors", p: "We use models from Anthropic (Claude) and Google (Gemini) via Emergent's universal interface. No personal content is used to train external models." },
    ],
  },
};
